#!/bin/bash

WORKSPACE=~/RP_ROS_Alvarez_Gonzalez_Kohley_25/game_ws

# Cargar entorno de ROS y del workspace
source /opt/ros/noetic/setup.bash
source $WORKSPACE/devel/setup.bash

NODE=$1

case $NODE in
    info)
        python3 $WORKSPACE/src/project_game/scripts/info_user.py
        ;;
    control)
        python3 $WORKSPACE/src/project_game/scripts/control_node.py
        ;;
    game)
        python3 $WORKSPACE/src/project_game/scripts/game_node.py
        ;;
    pygame)
        python3 $WORKSPACE/src/project_game/scripts/pygame_node.py
        ;;
    result)
        python3 $WORKSPACE/src/project_game/scripts/result_node.py
        ;;
    *)
        echo "Usage: ./run_nodes [info|control|game|pygame|result]"
        ;;
esac
